var zhTWNo=2051,zhCNNo=2219;sortByElmentNo(master.mstSvt);
function svtDataTable(a){var b="";$(".ceInfo").html("");var d=master.mstSvt[findName(master.mstSvt,9200040)];for(f in master.mstSvt)if(master.mstSvt[f].id==a){d=master.mstSvt[f];break}document.title=d.name+" - \u79ae\u88dd\u8cc7\u6599\u67e5\u8a62";for(var e in master.mstSvtLimit)if(master.mstSvtLimit[e].svtId==a)break;if(d.script.maleImageId)$("#ceGraph").html('<div class="slide"><div><img src="https://fgo.kazemai.io/Asset/JP/CharaGraph/'+a+"/"+a+'a.png" onerror=javascript:this.src="https://fgo.kazemai.io/common/images/CharaGraph/0.png" style="width:100%" /></div><div><img src="https://fgo.kazemai.io/Asset/JP/CharaGraph/'+
d.script.maleImageId+"/"+d.script.maleImageId+'a.png" onerror=javascript:this.src="https://fgo.kazemai.io/common/images/CharaGraph/0.png" style="width:100%" /></div>');else if(d.script.imagePartsGroupId){imgPts={};for(var h in master.mstImagePartsGroup)master.mstImagePartsGroup[h].id==d.script.imagePartsGroupId&&(tmpImg=master.mstImagePartsGroup[h],tmpImg.script.NotEquipImage&&1==tmpImg.script.NotEquipImage||(tmpImg.typeValue in imgPts?imgPts[tmpImg.typeValue].push(tmpImg.imageValue):imgPts[tmpImg.typeValue]=
[tmpImg.imageValue]));var f='<div class="rdobutton">\n';for(var c in imgPts)if(imgPts.hasOwnProperty(c)){f+="<br/>\u5206\u652f"+c+"<br/>\n";for(var g in imgPts[c])f+='<input class="rdobutton_radio" type="radio" id="radioId'+imgPts[c][g]+'" name="radioname'+c+'" value="'+imgPts[c][g]+'" '+(1==imgPts[c][g]?"checked":"")+' />\n<label class="rdobutton_label" for="radioId'+imgPts[c][g]+'">'+imgPts[c][g]+"</label>\n"}f+="</div>";$("#ceGraph").html(f+'<br/><img src="https://fgo.kazemai.io/common/images/CharaGraph/0.png" id="ceGraphIP" style="width:100%" />');
$(".rdobutton_radio").change(function(){var k="";$('input[type="radio"][class="rdobutton_radio"]:checked').each(function(){k+="_"+$(this).val()});$("#ceGraphIP").attr("src","https://fgo.kazemai.io/Asset/JP/CharaGraph/"+a+k+"/"+a+k+"a.png")});$('input[type="radio"][class="rdobutton_radio"][value="1"]').each(function(){$(this).attr("checked","checked").trigger("change")})}else $("#ceGraph").html('<img src="https://fgo.kazemai.io/Asset/JP/CharaGraph/'+a+"/"+a+'a.png" onerror=javascript:this.src="https://fgo.kazemai.io/common/images/CharaGraph/0.png" style="width:100%" />');
$("#ceNo").html(d.collectionNo);for(c=0;c<master.mstSvtLimit[e].rarity;c++)b+="\u2605";$("#ceRarity").html(b);$("#ceName").html(d.name);$("#ceHp").html(master.mstSvtLimit[e].hpBase+" / "+master.mstSvtLimit[e].hpMax);$("#ceAtk").html(master.mstSvtLimit[e].atkBase+" / "+master.mstSvtLimit[e].atkMax);for(c in master.mstIllustrator)if(master.mstIllustrator[c].id==d.illustratorId)break;$("#ceIll").html((1<master.mstIllustrator[c].id?'<a href="illustrator.html#'+master.mstIllustrator[c].id+'">':"")+master.mstIllustrator[c].name);
e=0;for(c in master.mstSvtSkill)if(master.mstSvtSkill[c].svtId==d.id&&16!=master.mstSvtSkill[c].flag)if(0==master.mstSvtSkill[c].condLimitCount){if(0==master.mstSvtSkill[c].eventId){if(g=master.mstSkill[findName(master.mstSkill,master.mstSvtSkill[c].skillId)],$("#ceSkIcon").html('<img src="https://fgo.kazemai.io/Asset/JP/SkillIcons/skill_'+padLeft(g.iconId,5)+'.png" onerror=javascript:this.src="https://fgo.kazemai.io/Asset/JP/SkillIcons/skill_999999.png" style="width:55px;" />'),b="",0<g.actIndividuality.length)for(var l in g.actIndividuality)null!=
findSvtNameZh(g.actIndividuality[l])&&(e=g.actIndividuality[l])}else b="<br> \uff0b ";$("#ceSkill").append(b+findSkDetailZh(master.mstSvtSkill[c].skillId))}else 4==master.mstSvtSkill[c].condLimitCount&&(b=0==master.mstSvtSkill[c].eventId?"":"<br> \uff0b ",$("#ceSkill2").append(b+findSkDetailZh(master.mstSvtSkill[c].skillId)));$("#ceType").html("\u6700\u5927\u89e3\u653e");0!=e&&($("#ceType").html("\u5c08\u5c6c\u5f9e\u8005"),$("#ceSkill2").html(svtFace(e)));for(const [k,m]of Object.entries(ValCE))if(-1!=
m.join().search(a)){$("#ceType").html("\u5c08\u5c6c\u5f9e\u8005");$("#ceSkill2").html(svtFace(k));break}d.collectionNo>zhCNNo&&($("#cmtlang_zh").prop("checked",!1),$("#cmtlang_jp").prop("checked",!0));cmtRead($("input[name=cmtlang]:checked").val());$("img.lazyload").lazyload();$(function(){$(".slide").slick({dots:!0,infinite:!0,speed:300,slidesToShow:1,adaptiveHeight:!0,autoplay:!0,autoplaySpeed:2E3})})}
function cmtRead(a){try{$.get("common/svtcomment/"+a+"/"+$("#svtid").val(),function(b){var d="";JSON.parse(base64.decode(b)).forEach(function(e,h,f){0!=f[h].priority&&null!=f[h].priority&&(d+="<hr>");d+=f[h].comment.replace(/\n/g,"<br>").replace(/<br>/,"<br><br>").replace(/\[FFff20\]/,'<font color="gold">').replace(/\[-\]$/,"</font>")+""});$("#ceComment").html(d)},"text")}catch(b){console.log("Cannot find comment file."),"zh"==a&&cmtRead("jp")}}
function optionInit(){$("#zhTWNO").html(zhTWNo);$("#zhCNNO").html(zhCNNo);for(var a in master.mstSvt)6!=master.mstSvt[a].type&&98!=master.mstSvt[a].type||svtid.options.add(new Option("No."+master.mstSvt[a].collectionNo+" "+master.mstSvt[a].name,master.mstSvt[a].id));var b="1";getUrl("no")&&(b=getUrl("no"));if(b)for(a in master.mstSvt)if((6==master.mstSvt[a].type||98==master.mstSvt[a].type)&&b==master.mstSvt[a].collectionNo){$("#svtid").val(master.mstSvt[a].id);break}svtidChange()}
function svtidChange(){var a;for(a=svtlv.options.length-1;0<=a;a--)svtlv.remove(a);for(a in master.mstSvtLimit)if(master.mstSvtLimit[a].svtId==svtid.value&&4==master.mstSvtLimit[a].limitCount){for(var b=1;b<=master.mstSvtLimit[a].lvMax;b++)svtlv.options.add(new Option("Lv."+b,b));break}svtlvChange();svtDataTable(svtid.value);drawChart()}
function svtlvChange(){for(var a in master.mstSvtLimit)if(master.mstSvtLimit[a].svtId==svtid.value){atk.value=master.mstSvtLimit[a].atkBase;hp.value=master.mstSvtLimit[a].hpBase;for(var b in master.mstSvt)if(master.mstSvt[b].id==svtid.value){for(var d in master.mstSvtExp)if(master.mstSvt[b].expType==master.mstSvtExp[d].type&&master.mstSvtExp[d].lv==svtlv.value){atk.value=Math.floor(master.mstSvtLimit[a].atkBase+(master.mstSvtLimit[a].atkMax-master.mstSvtLimit[a].atkBase)*master.mstSvtExp[d].curve/
1E3);hp.value=Math.floor(master.mstSvtLimit[a].hpBase+(master.mstSvtLimit[a].hpMax-master.mstSvtLimit[a].hpBase)*master.mstSvtExp[d].curve/1E3);break}break}break}}
function findSkDetailZh(a){var b=0,d;for(d in master.mstSkillLv)if(master.mstSkillLv[d].skillId==a){b=master.mstSkillLv[d].skillDetailId;break}for(var e in skDetail)if(b==skDetail[e][0]){var h=skDetail[e][1];break}if(document.getElementById("isJpTxt").checked||!h)for(e=0;e<master.mstSkillDetail.length;e++)if(b==master.mstSkillDetail[e].id){h=master.mstSkillDetail[e].detail;break}return h}
function svtlocation(a){a="";for(var b in master.mstSvt)if(master.mstSvt[b].id==svtid.value){a=0!=master.mstSvt[b].collectionNo?a+("?no="+master.mstSvt[b].collectionNo):a+("?id="+master.mstSvt[b].id);break}"file:"==location.protocol?changeURL(location.protocol+"//"+location.pathname+a):changeURL(location.protocol+"//"+location.hostname+location.pathname+a);svtidChange()};
