function indi_show(b){$(".indi_td").empty();var c=0<indi_list[b].svt.length,f=0<indi_list[b].enemy.length;c&&$("#indi_svt").append(indi_list[b].svt+"<br>");f&&$("#indi_enemy").append(indi_list[b].enemy+"<br>");for(var a in master.mstSvt){var d=master.mstSvt[a],e=!1;var h=-1!=$.inArray(parseInt(b),d.individuality);if(-1!=$.inArray(d.type,[1,2])&&0!=d.collectionNo){if(h==c||e||($("#indi_svt").append('<a href="svtData.html?no='+d.collectionNo+'"><div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/common/images/Asset/Faces/f_'+
d.id+'0.png\')"  title="'+findSvtNameZh2(d.id)+'"></div></a>'),e=!0),!e){for(var g in master.mstSvtLimitAdd)if(master.mstSvtLimitAdd[g].svtId==d.id&&0<master.mstSvtLimitAdd[g].individuality.length&&-1!=$.inArray(parseInt(b),master.mstSvtLimitAdd[g].individuality)&&!c)if(11>master.mstSvtLimitAdd[g].limitCount)$("#indi_svt").append('<a href="svtData.html?no='+d.collectionNo+'"><div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/Asset/JP/Faces/f_'+d.id+'0.png\')"  title="'+findSvtNameZh2(d.id)+
'">'+master.mstSvtLimitAdd[g].limitCount+"</div></a>");else for(var k in master.mstSvtCostume)if(master.mstSvtCostume[k].svtId==d.id&&master.mstSvtCostume[k].id==master.mstSvtLimitAdd[g].limitCount){$("#indi_svt").append('<a href="svtData.html?no='+d.collectionNo+'"><div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/Asset/JP/Faces/f_'+master.mstSvtLimitAdd[g].battleCharaId+'0.png\')"  title="'+findSvtNameZh2(d.id)+'"><img src="https://fgo.kazemai.io/Asset/JP/Items/23.png" style="width:50%;"></div></a>');
break}for(g in master.mstSvtIndividuality)master.mstSvtIndividuality[g].svtId==d.id&&0<master.mstSvtIndividuality[g].individuality.length&&(-1==$.inArray(parseInt(b),master.mstSvtIndividuality[g].individuality)||c||(-1==master.mstSvtIndividuality[g].limitCount?$("#indi_svt").append('<a href="svtData.html?no='+d.collectionNo+'"><div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/Asset/JP/Faces/f_'+d.id+'0.png\')"  title="'+findSvtNameZh2(d.id)+'"></div></a>'):11>master.mstSvtIndividuality[g].limitCount&&
$("#indi_svt").append('<a href="svtData.html?no='+d.collectionNo+'"><div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/Asset/JP/Faces/f_'+d.id+'0.png\')"  title="'+findSvtNameZh2(d.id)+'">'+master.mstSvtIndividuality[g].limitCount+"</div></a>")))}}else-1!=$.inArray(d.type,[-1,4,5,9])&&h!=f&&null!=enemyName[d.id]&&$("#indi_enemy").append('<div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/common/images/icon/enemy/'+d.id+'1.png\')"  title="'+enemyName[d.id]+
'"></div>')}$("img.lazyload").lazyload()}function difference(b,c){for(var f=[],a=0;a<b.length;a++)-1===c.indexOf(b[a])&&f.push(b[a]);return f}function sameArray(b,c){var f=[],a=[],d;for(d in b)for(var e in c){if(b[d]==c[e]){-1==f.indexOf(c[e])&&f.push(c[e]);break}c[e].split("@")[0]==b[d]?(-1==f.indexOf(c[e])&&f.push(c[e]),a.push(b[d])):b[d].split("@")[0]==c[e]&&(-1==f.indexOf(b[d])&&f.push(b[d]),a.push(c[e]))}for(var h in a)b=f.indexOf(a[h]),-1!=b&&f.splice(b,1);return f}
function indi_filter(b){$(".indi_td").empty();filteredArr=[];tmpArr=[];for(var c in b){$("#filterTxt").append(indi_list[b[c]].name+"<br/>");b[c]=parseInt(b[c]);tmpArr.length=0;for(var f in master.mstSvt){var a=master.mstSvt[f];-1!=$.inArray(b[c],a.individuality)&&(-1!=$.inArray(a.type,[1,2])&&0!=a.collectionNo?tmpArr.push(""+a.id):-1!=$.inArray(a.type,[-1,4,5,9])&&tmpArr.push(""+a.id+"E"))}for(var d in master.mstSvtLimitAdd){a=master.mstSvtLimitAdd[d];var e=findElement(master.mstSvt,a.svtId);if(-1==
$.inArray(""+a.svtId,tmpArr)&&null!==e&&-1!=$.inArray(e.type,[1,2])&&0!=e.collectionNo)if(-1!=$.inArray(b[c],a.individuality))-1==tmpArr.indexOf(""+a.svtId+"@"+a.limitCount+"@"+a.battleCharaId)&&tmpArr.push(""+a.svtId+"@"+a.limitCount+"@"+a.battleCharaId);else if(-1!=master.mstSvtLimitAdd[d].attri)for(var h in master.mstAttri)if(master.mstAttri[h].id==a.attri&&master.mstAttri[h].individuality==b[c]){-1==tmpArr.indexOf(""+a.svtId+"@"+a.limitCount+"@"+a.battleCharaId)&&tmpArr.push(""+a.svtId+"@"+a.limitCount+
"@"+a.battleCharaId);break}}for(d in master.mstSvtIndividuality)if(a=master.mstSvtIndividuality[d],e=findElement(master.mstSvt,a.svtId),-1==$.inArray(""+a.svtId,tmpArr)&&null!==e&&-1!=$.inArray(e.type,[1,2])&&0!=e.collectionNo&&-1!=$.inArray(b[c],a.individuality))if(-1==a.limitCount)tmpArr.push(""+a.svtId);else for(var g in master.mstSvtLimitAdd)if(master.mstSvtLimitAdd[g].svtId==a.svtId&&master.mstSvtLimitAdd[g].limitCount==a.limitCount){-1==tmpArr.indexOf(""+a.svtId+"@"+a.limitCount+"@"+a.battleCharaId)&&
tmpArr.push(""+a.svtId+"@"+a.limitCount+"@"+a.battleCharaId);break}for(d in master.mstSvtTransform)a=master.mstSvtTransform[d],e=findElement(master.mstSvt,a.aftSvtId),-1==$.inArray(""+a.aftSvtId,tmpArr)&&null!==e&&-1!=$.inArray(b[c],e.individuality)&&tmpArr.push(""+e.id);filteredArr=0==c?tmpArr.slice():sameArray(filteredArr,tmpArr)}console.log(filteredArr);for(var k in filteredArr)if(~filteredArr[k].indexOf("@")){c=filteredArr[k].split("@");b=parseInt(c[0]);a=parseInt(c[1]);c=parseInt(c[2]);f=!1;
if(0<c)for(var l in master.mstSvtCostume)if(master.mstSvtCostume[l].svtId==b&&master.mstSvtCostume[l].id==a){$("#indi_svt").append('<a href="svtData.html?no='+findElement(master.mstSvt,b).collectionNo+'"><div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/Asset/JP/Faces/f_'+c+'0.png\')"  title="'+findSvtNameZh2(b)+'"><img src=https://fgo.kazemai.io/Asset/JP/Items/23.png" style="width:50%;"></div></a>');f=!0;break}if(!f){switch(a){case 1:c=1;break;case 2:c=1;break;case 3:c=2;
break;case 4:c=3;break;default:c=0}$("#indi_svt").append('<a href="svtData.html?no='+findElement(master.mstSvt,b).collectionNo+'"><div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/common/images/Asset/Faces/f_'+b+c+'.png\')"  title="'+findSvtNameZh2(b)+'">'+(-1==a?"":a)+"</div></a>")}}else~filteredArr[k].indexOf("E")?(a=filteredArr[k].substring(0,filteredArr[k].length-1),null!=enemyName[a]&&$("#indi_enemy").append('<div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/common/images/icon/enemy/'+
a+'1.png\')"  title="'+enemyName[a]+'"></div>')):(b=filteredArr[k],a=findElement(master.mstSvt,b),$("#indi_svt").append('<a href="svtData.html?'+(0==a.collectionNo?"id="+a.id:"no="+a.collectionNo)+'"><div class="itemMTR" style="background-image: url(\'https://fgo.kazemai.io/common/images/Asset/Faces/f_'+b+'0.png\')"  title="'+findSvtNameZh2(b)+'"></div></a>'));$("img.lazyload").lazyload()}
function indiOut(){$.each(indi_list,function(b,c){c.name.startsWith("@")||$("#indi_id").append($("<option></option>").attr("value",b).text(c.name))});$(".attention_btn_ce").on("click",function(){$("#errorTxt").empty();targetId=$("#indi_id").val();indiArr=0<$("#indiArray").text().length?$("#indiArray").text().split(","):[];if(5<=indiArr.length)$("#errorTxt").html("\u689d\u4ef6\u4e0a\u9650\u6700\u591a5\u500b<br/>");else{if(0!=targetId){if(-1==$.inArray(targetId,indiArr))indiArr.push(targetId);else{$("#errorTxt").html("\u91cd\u8907\u7684\u689d\u4ef6<br/>");
return}indi_filter(indiArr)}$("#indiArray").text(indiArr)}});$(".attention_btn_st").on("click",function(){$("#errorTxt").empty();$("#indiArray").empty();$(".indi_td").empty()})}$("#classAtkBtn").click(classRelation2);$("#classAtkBtnSP").click(classRelationSP);function classRelationSP(){$("#classAtkSP").css("display","block");$("#classAtkSP").css("overflow-x","auto");$("#classAtkSP").css("white-space","nowrap");$("#classAtkBtnSP").css("display","none")}
function classRelation2(){var b=[],c,f="",a={"+1":"Saber","+2":"Archer","+3":"Lancer","+4":"Rider","+5":"Caster","+6":"Assassin","+7":"Berserker","+8":"Shielder","+9":"Ruler","+11":"Avenger","+10":"Alterego","+23":"MoonCancer","+25":"Foreigner","+28":"Pretender","+33":"Beast(\u5fb7\u62c9\u79d1)","+38":"Beast(\u57c3\u5217)","+40":"UnBeast(\u746a\u9e97)"};for(e in a)a.hasOwnProperty(e)&&b.push(e);for(c=0;c<b.length;c++){var d="";var e=b[c];var h=master.mstClass[findName(master.mstClass,e)];0!=c&&(d+=
"<tr>");d+=classIcon(h,a[e]);d+="<td>";d=1E3<h.attackRate?d+('<span class="red">'+h.attackRate/1E3+"</span>"):1E3>h.attackRate?d+('<span class="blue">'+h.attackRate/1E3+"</span>"):d+"\uff0d";d+="</td>";for(e=0;e<b.length;e++){h=!1;for(var g in master.mstClassRelation)if(master.mstClassRelation[g].atkClass==master.mstClass[findName(master.mstClass,b[c])].relationId&&master.mstClassRelation[g].defClass==master.mstClass[findName(master.mstClass,b[e])].relationId){h=!0;d+="<td>";d=1E3<master.mstClassRelation[g].attackRate?
d+('<span class="red">'+master.mstClassRelation[g].attackRate/1E3+"</span>"):1E3>master.mstClassRelation[g].attackRate?d+('<span class="blue">'+master.mstClassRelation[g].attackRate/1E3+"</span>"):d+"\uff0d";d+="</td>";break}h||(d+="<td>\uff1f</td>")}d+="</tr>";f+=d}d="";for(c=0;c<b.length;c++)e=b[c],h=master.mstClass[findName(master.mstClass,e)],d+=classIcon(h,a[e]);$("#classAtk").append("<tr><th colspan=2 rowspan=2>\u8077\u968e</th><th rowspan=2>\u50b7\u5bb3<br>\u500d\u7387</th><th colspan="+b.length+
">\u9632\u79a6\u5074</th></tr><tr>"+d+"</tr><tr><th rowspan="+b.length+">\u653b<br>\u64ca<br>\u5074</th>"+f);$("#classAtk").css("display","block");$("#classAtk").css("overflow-x","auto");$("#classAtk").css("white-space","nowrap");$("#classAtkBtn").css("display","none")}
function classIcon(b,c){txt="";if(-1<[33,38,40].indexOf(b.id)){tmpSvtId="";for(var f in master.mstSvt)if(master.mstSvt[f].classId==b.id){tmpSvtId=master.mstSvt[f].id;break}txt+='<th style="width:20px;height:20px;"><img src="https://fgo.kazemai.io/Asset/JP/Faces/f_'+tmpSvtId+'0.png" title="'+c+'" class="classS"/></th>'}else txt+='<th style="width:20px;height:20px;"><img src="https://fgo.kazemai.io/Asset/JP/ClassIcons/class3_'+b.iconImageId+'.png" title="'+c+'" class="classS"/></th>';return txt}
function atrriRelation(){for(var b,c,f=document.getElementsByClassName("attriR"),a=0;a<f.length;a++){b=f[a].id.replace(/ar/g,"").split(/-/);c=1E3;for(var d in master.mstAttriRelation)if(master.mstAttriRelation[d].atkAttri==b[0]&&master.mstAttriRelation[d].defAttri==b[1]){c=master.mstAttriRelation[d].attackRate;break}1E3==c?document.getElementById(f[a].id).innerHTML="\uff0d":1E3<c?document.getElementById(f[a].id).innerHTML="<span class='red'>"+c/1E3+"</span>":1E3>c&&(document.getElementById(f[a].id).innerHTML=
"<span class='blue'>"+c/1E3+"</span>")}};
